/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App(pretty);
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
